name: Crawl
on:
  schedule:
  - cron: 0 2 */7 * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: ensure alliedmods.json exists
        run: touch misc/alliedmods.json
      - name: generate alliedmods.json
        run: docker run -v ${{ github.workspace }}/misc/alliedmods.json:/usr/src/app/releases.json hackebein/alliedmods-json "mmsource|sourcemod|SteamWorks" "linux"
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update AlliedMods build list
          file_pattern: misc/alliedmods.json
